src/build/supportedExtensions.js
Unfortunately, Jade has been renamed to Pug (ref: pugjs/pug#2184).
=> Added support for Pug (ex. Jade)

src/build/supportedExtensions.js
This PR includes:
- `.o, .a, .exe, .lib, .obj, .dll, .pyc` for Binary
- `.hpp, .cc, .cxx` for C++
- `.otf, .eot, .pfa, .pfb, .wfd` for Fonts
- `.htm` for HTML (correction)
- `.zsh, .fish` for Shell
- `.tar, .gz, .bzip2, .bz2, .xz` for Zips
Another problem is that `.m` is used for **both** Objective-C and MATLAB. It is not a simple task to distinguish them. Perhaps we need an option item to specify how to classify them?
=> Add more file extensions to C++, Font, Binary, Shell and Zip

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
***Fixes #134 second time***
looks like headlines aren't supported
=> Remove headlines in templates

src/build/supportedExtensions.js
***Fixes #159***
This adds the erb icon to the .erb extension in supportedExtensions.js Line: 34. Logged in Issue #159
=> Add .erb extension to ERB icon list

src/build/supportedExtensions.js
some repos e.g https://github.com/google/WebFundamentals use `.markdown` for markdown files.
and this is what [John Gruber endorses](http://daringfireball.net/linked/2014/01/08/markdown-extension).
=> support `.markdown` for Markdown files

src/build/supportedExtensions.js
`.hxml` are just config files for the Haxe compiler, source files use `.hx`.
=> Use the haxe icon for Haxe source files

src/build/supportedExtensions.js
.gitkeep isn't an official Git feature, but a fairly common naming convention (see http://stackoverflow.com/questions/7229885/what-are-the-differences-between-gitignore-and-gitkeep).
Btw, GitHub supports squashing commits to avoid the merge commit (just an fyi, it's a matter of preference).
=> Add gitkeep as a Git extension

src/build/supportedExtensions.js
.merlin is a config file for https://github.com/the-lambda-church/merlin. Doesn't look like it has a logo of its own,, so it makes sense to just use the OCaml one I guess.
=> Use the OCaml icon for .merlin

src/build/supportedExtensions.js
.n is used for Neko binaries (http://nekovm.org) - the Neko VM is commonly used in conjunction with Haxe and packaged with the compiler.
=> Use the binary icon for Neko binaries

src/build/supportedExtensions.js
For example web.config in .Net Core projects
Also .pdb files from .Net
=> Adding config icon for config files and binary for pdb

src/build/supportedExtensions.js
.so is a shared object / the unix counterpart for .dlls
.ndll is a NekoVm library file: http://nekovm.org/doc/vm
=> Add .so and .ndll to binary extensions

src/build/supportedExtensions.js
include.xml is a file for Lime-based haxe libraries with additional configuration that is added to a project when the lib is included.
=> Add support for Lime include.xml files

src/build/supportedExtensions.js
See https://ocaml.org/learn/tutorials/filenames.html
I don't think it's helpful to use the OCaml icon for binary files - if they're in the same directory as the source files, source files become hard to spot.
Example from the Haxe compiler's source:
=> Add OCaml binary files to binaries, add .mli / .mll to OCaml

src/build/supportedExtensions.js
It's often used for encrypted key files (for instance deploy keys), so the icon seems fitting.
=> Use the key icon for .enc

src/build/supportedExtensions.js
There is also a `settings.json`, but I didn't add that because the name might be a little too generic, leading to files using the icon incorrectly... Perhaps it could check that these files (`launch.json`, `tasks.json`, `settings.json`) are within a `.vscode` folder somehow?
=> Use the VSCode icon for tasks.json

src/build/supportedFolders.js
[short comment]
in polymer-tools "dist" folder name is "build"
=> adds "build" folder name for "dist" icon

src/build/supportedExtensions.js
***Fixes #404***
GitLab CI filenames begin with a `.` Similar to the name `.travis.yml`, it is `.gitlab-ci.yml`.
=> Fix gitlab-ci icon association

src/build/supportedExtensions.js
This PR adds `.mdown` to the markdown file extensions.
**Why?** I have a ton of `.mdown` files in one of my projects. I would rather not, but alas ... not the point.
**More?** Based on some quick googling there are [several other](http://superuser.com/questions/249436/file-extension-for-markdown-files) extensions for markdown files, but [not without some controversy](http://daringfireball.net/linked/2014/01/08/markdown-extension). Happy to add those too if you'd like.
=> add mdown as markdown file extension

CHANGELOG.md, icons.json, src/build/supportedExtensions.js
=> .class associated with Java icon

icons.json, src/build/supportedExtensions.js
***Fixes #475***
This is for making .exp (expect) scripts show up with the tcl icon
=> added '.exp' extension to tcl

.eslintrc.json, icons.json, package.json, src/build/build.js, src/build/exampleGenerator.js, src/build/iconGenerator.js, src/dev/extension.js, src/dev/messages.js
I took the liberty to refactor the functions of the build process.
List of changes:
- Made the functions more generic.
- Added the ability to generate the icons file to any directory, passing it as an argument to the `generate` function.
- Added functions comments.
- Added ability to find the relative path to the icons folder (handy if we decide to move the `icons.json` file to dist).
- Added `npm` script entry for `eslint` (this will help if we adopt a CI service).
- Added some `eslint` rules to get rid of inline rule exceptions.
- Added ability to auto-update the `package.json` file, if the icon theme path changes.
- Added sorting to the folders and files list on generating (now we don't care of the supported icon positioning in the list).
@robertohuertasm Keep what you like. Through it …
=> Refactored the build process.

icons.json, src/build/supportedExtensions.js
Some projects use a dotted filename `.appveyor.yml`. (see: https://github.com/angular/angular-cli)
=> Improves the support for appveyor.

package.json, src/build/iconGenerator.js, src/dev/extension.js
There are two key reasons for this PR.
1. `Lodash` v4 is officially a superset of `Underscore` (there was a plan to merge `Lodash` and `Underscore` as `Underdash` but it ended being `Lodash` v4)
2. `Lodash` is already included in `node_modules`, so it's an overkill to have also `Underscore`.
=> Replase the use of underscore with lodash.

.eslintrc.json, package.json, src/build/supportedExtensions.js, src/dev/extension.js, src/dev/settings.js
This PR updates the dependency of `eslint`.
With the update the following issues get resolved:
- ESLint issue with importing `vscode` which was marked as disbaled.
The ESLint update also enables some rules by default which have been dealt in code or eslint config.
=> Update eslint dependencies.

.eslintrc.json, package.json, src/build/iconGenerator.js, src/build/languages.js, src/build/supportedExtensions.js, tests/iconGenerator.test.js
This PR does the following:
- Adds more test cases to ensure the `icons.json` is generated correctly.
- Contains fixes of #501.
- Fixes an error with the `jar` extension declaration.
- Avoids `lodash` usage where possible.
=> Add more test cases.

.editorconfig, .vscode/settings.json, package.json
This PR introduces `editorconfig` ruling. This way we will get rid of the constant changing of spacing in `package.json`.
@robertohuertasm If you want `package.json` spacing as the rest of the `json` files just remove the `[package.json]` rule.
=> Introduce editorconfig rules.

src/icon-manifest/supportedFolders.ts
Expanding the association of the `images` folder icon to be used also for `icons` folder.
This PR is a proposal.
=> Associate 'icons' folder to 'images' folder icon.

icons/file_type_light_vsix.svg, src/icon-manifest/supportedExtensions.ts
Added light version because the icon doesn't look good in a light theme.
=> Add light version of the 'vsix' icon.

src/icon-manifest/supportedFolders.ts
`i18n` = internationalization
`g11n` = globalization
As seen at https://en.wikipedia.org/wiki/Internationalization_and_localization
=> Associate more names to locale folder icon.

.vscodeignore, CHANGELOG.md, package.json, src/settings/extensionSettings.ts
=> Fixes issue with prepublish script and prepares 7.0.1 publication

package.json, src/models/vscode/vscodeUri.ts
Reasons: 
1. This extension supports `vscode` version `1.5.0` and above.
2. Setting the `vscode engine` version to `1.5.0` fetches more updated type definintions for `vscode` (`vscode.d.ts`).
After merging execute: `npm install` or `yarn install`.
=> Update package.json to use as minimum vscode engine version 1.5.0

.vscode/settings.json
While developing we want the Angular icons or any other project specific icons to always be shown by default, thus disabling the auto detection on the workspace level is justified.
=> [Proposal] Disable project auto-detection on this workspace.

src/icon-manifest/manifestMerger.ts
Typings2 folder was shown whenever I toggled some preset. This PR fixes the issue.
=> Disabled folders were being shown when applying customizations

src/icon-manifest/supportedExtensions.ts
With [@alexlur/rollup-plugin-typescript](https://github.com/alexlur/rollup-plugin-typescript) (and possibly the "official" plugin) you can configure Rollup from a TS file. This PR enables the Rollup icon for that usecase.
=> Add TypeScript extension to Rollup icon

src/icon-manifest/supportedExtensions.ts
I think this should fix it anyway, the config for `.travis.yml` also has a leading dot and it works for that.
=> Fix missing dot for .codeclimate.yml, closes #732

src/icon-manifest/supportedExtensions.ts
=> Use the regular json icon for launch.json and tasks.json

.vscodeignore
Sorry guys, my bad. Forgot to add it in `.vscodeignore`.
=> Exclude '.bithoundrc' from distribution.

src/commands/index.ts, src/icon-manifest/manifestMerger.ts, src/index.ts, src/init/autoApplyCustomizations.ts, src/init/autoDetectProject.ts, test/autoDetectProject.test.ts
I have noticed that when a project doesn't have a user level `settings.json` file or a `.vscode` directory in general, the way we handle the project detection leaves some `garbage` behind when the user cancels the action on the prompt message.
This PR improves the detection flow and handles canceling cases by removing its `echo`.
=> Improve detection flow and add a vscode directory handler on cancel.

src/icon-manifest/supportedExtensions.ts
Last version of @angular-cli (rc1) introduces two variants of `tsconfig.json` to target the `app` and the `tests`
=> Add support for angular cli tsconfig variants

src/icon-manifest/manifestMerger.ts
=> Add guard clause to prevent crash when "extensions" is not provided.

src/commands/index.ts, src/index.ts
Now that we have inverted the preset for Angular icons the `.vscode` directory handling has to be added to the toggle function as well.
=> Add the vscode directory handling on presets toggle.

src/commands/index.ts
I noticed a bug with the new feature of using the default icon for all folders.
That preset was overriding the `hide all folders` preset, so I change the order that the presets are applied.
It makes sense that even if the user has set all folder to have the default icon when setting to hide the folder icons it has to be the last applied preset.
=> Change the order the folder icons presets are applied.

src/icon-manifest/supportedFolders.ts
_This PR partially addresses one of the goals in #650 by adding an icon for `lib` folders. If this isn't acceptable it can be dropped._
Reason: `lib` and `release` are common patterns for distribution folders; as an example, Angular UI Router has used both: [release](https://github.com/angular-ui/ui-router/blob/624d94ea924b4d0c113e3bf7ee8c0439e73e8247/package.json#L92), [lib](https://github.com/angular-ui/ui-router/blob/master/package.json#L62)
Ambiguities: Some libraries use `lib` in different ways; for instance, as a source folder or a side-by-side resource with `dist` in the published library. However, the common case (as I understand it) is for `lib` to be some kind of resource meant to be consumed by an end user, mildly analogous to …
=> Expand extensions list for `dist` folder icon

package.json, yarn.lock
Fixes #892.
The issue is a false positive (don't ask me why).
Edit: Just figured out why it failed. `Appveyor` failed to get the package on one of the builds resulting in a build failure.
=> chore(package): update @types/sinon to version 2.1.3

src/icon-manifest/supportedExtensions.ts
So jest is a bit weird with their configs. They seem to have been half-assing it till now and in the last version they broke `.jestrc` entirely (There has to be a file extention or bust).
[Their docs dictate `jest.config.js`](https://facebook.github.io/jest/docs/en/configuration.html#content) as the only auto-discovered config filename.
=> Add default config filename for jest

package.json
Fix missing i18n of configuration item `vsicons.presets.foldersAllDefaultIcon`
=> Fix missing i18n of configuration

src/commands/index.ts
=> Fix restart loop issue with manual config changes detection.

README.md
Updated badge links in README to resolve to `https` according to https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_14.md#changes-for-extension-authors.
**Note:** I have requested so that the `vscode` team adds also `codecov.io` to trusted badge provider list (https://github.com/Microsoft/vscode-docs/issues/1055).
`issuestats` may not render correctly or link to the site will be presented with warming until the author switches to self-signed SSL cert.
=> Update badges links of README to resolve to HTTPS.

.appveyor.yml, .travis.yml, README.md, package.json, src/vscode.d.ts
Dropping support of `vscode` versions prior of `1.8.1`.
=> Drop support for vscode prior of version 1.8.1.

test/init/applyCustomizationsManager.test.ts
Related to #1072.
If we introduce the proposed change then order alterations will trigger change detection. That's why `intersectionWith` was being used. I've added the test so we won't miss this next time.
=> test verifying altered order won't trigger config changes

.bithoundrc, src/settings/settingsManager.ts, test/settings/settings.test.ts
***Fixes #1097***
We were not using valid `SemVer` version for the default state.
=> Fix the version format for the default state.

src/icon-manifest/supportedExtensions.ts
Adds the additional filenames listed at https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#loading-the-configuration-object
=> Add additional stylelintrc filenames

Dockerfile, README.md, docker/development/Dockerfile, docker/development/README.md, docker/development/build.sh, docker/development/install.sh, docker/remote-builder/Dockerfile, docker/remote-builder/README.md, docker/remote-builder/build.sh
Just improved the docker images:
- reduced file size by using `node:alpine`.
- fixed issue with `vscode.d.ts` error when using some linux docker images.
- added a docker image in order to get the latest artifact from the published version, not the local. This may be useful for cases like [vscode-icons for Github](https://github.com/dderevjanik/github-vscode-icons) extension where the author requires the latest `icons.json` file.
//cc @dderevjanik
=> Docker Images

src/icon-manifest/supportedFolders.ts
https://github.com/vscode-icons/vscode-icons/issues/650#issuecomment-338482447
=> Map `language` and `lang`  to `locale` folder icon

.vscode/tasks.json
`taskName` changed by `label`.
Related to [#1330](https://github.com/vscode-icons/vscode-icons/pull/1330#issuecomment-341984132)
=> taskname has been deprecated

.travis.yml
`Travis CI` pre-build containers use `Yarn v0.27.5` which is outdated by far.
This PR forces `Travis CI` to use version `1.3.2` which by the time this is written is the latest.
=> Update Yarn version in CI.

.gitmodules, .travis.yml, package-lock.json, package.json, yarn.lock
This PR updates `wpilgenerator` to version `0.1.0` which has the following changes:
- Switched `shellscript` to `javascript` and moved it to `bin` folder.
- Simplified `travis` condition checks.
- Replaced custom argument parser with `yargs`.
- Changed the output directory to `lib`.
- Added ability to automatically find the `supportedExtensions` and `supportedFolders` files.
- Fixed debug launcher config.
- Improved exception handler.
- Added ability to automatically locate `travis` build directory.
- Fixed condition check evaluation.
=> Update submodule wpilgenerator.

src/icon-manifest/iconGenerator.ts, src/icon-manifest/manifestReader.ts, src/init/projectAutoDetection.ts, src/models/settings/settings.ts, src/models/vscode/index.ts, src/models/vscode/vscode.ts, src/models/vscode/vscodeWorkspace.ts, src/settings/settingsManager.ts, src/utils/index.ts, src/utils/vscode-extensions.ts, src/vscode.d.ts, test/iconGenerator/functionality.test.ts, test/settings/settings.test.ts
_**References #1416**_
This PR adds the functionality to set the `vsicons.customIconFolderPath` with a relative path to the root of the opening project. This is handy when distributing custom icons with the project source code.
I have also done some code refactoring which normally should have been submitted in another PR but I'm getting lazy lately.
Also, once this PR gets merged the [wiki page](https://github.com/vscode-icons/vscode-icons/wiki/Custom) needs to be updated to include the added ability.
=> Add support to specify a relative path for custom icons folder path.

wallaby.js
According to this [comment](https://github.com/vscode-icons/vscode-icons/pull/1523#issuecomment-374202394) this PR removes the `arch` check.
=> removed arch check

src/icon-manifest/supportedExtensions.ts
I've been a victim of `copy-paste`.
=> Fix Prettier config file association

src/icon-manifest/supportedExtensions.ts
Angular 6 CLI now create a config file named `angular.json` instead of the previous `.angular-cli.json`. This PR intend to support the new file name.
=> Add new Angular6 CLI config file name which is now angular.json.

src/icon-manifest/supportedExtensions.ts
Angular team said that this is valid in https://github.com/angular/angular-cli/releases/tag/v6.0.0-rc.2
_**Fixes no known issue**_
=> added .angular.json

.gitmodules, .travis.yml, package-lock.json, package.json, yarn.lock
This RP removes the dependency of the `wpilgenerator` from the project.
**Reasoning:**
`wpilgenerator` was created to be an automation script to publish the files and folders icons list, to our wiki from the CI. It shouldn't be part of the project in the first place, simply because, as it turned out, it was causing too much of a hassle to the average user, when trying to build the project. Not to mention the issue that arose on the CI builds for node v10.x, the security issues of the `nodegit` version used and the excessive build time of all jobs.
**Resolution:**
- `wpilgenerator` build and run scripts, on `v0.4.0` , have been reworked so that it can be installed as an `npm` package, without been publish to the `npmjs` registry.
- The `Travis-CI` config was adjusted, so to install …
=> Remove 'wpilgenerator' from dependencies

src/icon-manifest/supportedExtensions.ts
Support `rollup.config.common`,`rollup.config.dev` and `rollup.config.prod` variations. 
Resolve #1704.
=> support more rollup variations

src/iconsManifest/supportedFolders.ts
Adds several useful folder icon aliases.
=> Add new supported folders aliases

.vscode/settings.json
Since we use `Prettier` adding those to `settings` will stop `vscode` asking to choose.
=> Add default formater in settings

src/configuration/configManager.ts, test/configuration/configManager.test.ts
_**Fixes #2017**_
The fix includes the following logic:
- Do nothing if it's an extension update.
- Do the cleanup only on a single installation
This fix will work when updating to the next release after the one that includes this fix.
=> Fix reactivation issue

src/iconsManifest/supportedExtensions.ts
_**Fixes #2022**_
Trying to add support for the `.e2e-spec.ts, .e2e-test.ts` files
Exploring the code. I found the extension file. This applies to all `ts` files, I do not know if this completely solves the problem. I await your review.
=> Add support for e2e test filenames

src/iconsManifest/supportedFolders.ts
Although there's no established convention yet it seems that many people are using `widgets` as normally you would use `components` in many other frameworks.  Indeed, one could argue that in the Flutter lingo widgets are components.
See [this](https://hackernoon.com/scalable-app-structure-in-flutter-dad61a4bc389)
=> support for widgets folder (flutter)

src/iconsManifest/supportedFolders.ts
\+ add haxe_libraries (used by a Haxe package manager called lix)
=> Haxelib icon should only be used for .haxelib

src/iconsManifest/supportedExtensions.ts
Improve support for [Sequelize](https://github.com/sequelize/sequelize). Currently only  `.sequelizerc` is supported, but `.sequelizerc.js` and `.sequelizerc.json` should also be supported.
=> Improve support for Sequelize

src/vscode/vscodeManager.ts, test/vscode/vscodeManager.test.ts
_**Fixes #2218**_
We now rely on the `vscode` version, set in `engines` property of the `package.json` manifest to determine the minimum supported `vscode` version.
=> Fix the minimum supported editor version

icons/default_file.svg
The default file icon wasn't pixel perfect, this PR address that. In the future, I do feel like some icons can be made pixel perfect due to its design simplicity.
=> Pixel perfect default file icon

README.md
Kind of random, but saw this on the README and wanted to fix it.
"3644194 installs" is hard to parse; abbreviate to "3.64M installs".
=> README.md: abbreviate "installs" badge

CHANGELOG.md
Fix typo in 9.5.0 Release notes:
Amend `incluce` to `include`
=> Fix typo in 9.5.0 Release Notes

src/iconsManifest/supportedExtensions.ts
Unfortunately bad association slipt through for `tox`. This fixes it.
=> Fix 'tox' file association

src/iconsManifest/supportedExtensions.ts
The default config for Test Kitchen is no longer .kitchen.yml. We changed it to kitchen.yml about a year ago and those aren't picked up by this extension.
None
=> Add kitchen.yml as a Test Kitchen file

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
=> Add support for Cloud Foundry Manifest Language

.travis.yml
Publish hasn't worked, I'm not sure why, but a quick look at the travis file shows that wiki pages were still using the former version of node.
=> fix(travis): fix travis nodejs version

.travis.yml
Attempting to merge `travis` matrix with jobs. Hopefully, this will reinstate the generation of the wiki pages and the `docker` images.
=> Merge travis matrix and jobs

CHANGELOG.md
_**Fixes - No Issue Present**_
Replaces link #2328 with  #2298
=> Replaces incorrect link in CHANGELOG.md

.eslintignore, .eslintrc.json, greenkeeper.json, package-lock.json, package.json
Having now a better understanding of `eslint` we can totally remove `tslint` dependency.
`tslint` is only required when `@typescript-eslint/eslint-plugin-tslint` is used, in order to load `tslint` rules specified in `.eslintrc.json` (those that are transferred from the `tslint.json` file when migrating). Since we don't use any rules from `tslint.json` anymore there is no reason to include those dependencies.
=> Remove tslint dependency

.travis.yml, package-lock.json, package.json
It's time to remove the `examples-generator` from the project dependencies. Alas, this does not render the tool deprecated.
The new way to install it is by performing `npm install vscode-icons/examples-generator --no-save` 
and run it as `./node_modules/.bin/example` instead of `npm run example`. Of course, before running the generator a build of the project needs to exist first.
I'll update the wiki accordingly and improvements to the `examples-generator` project will be done in time.
=> Remove 'examples-generator' dependency

.travis.yml
An improvement in how `npm` packages are run in `CI`.
More info: https://github.com/npm/npx#readme
=> Use 'npx' to run 'npm' packages

.travis.yml
This PR adds `Windows` builds in `Travis CI`. `AppVeyor` builds are not removed until we are certain that `Travis` builds are reliable.
=> Add Travis CI Windows builds

src/iconsManifest/languages.ts
_**References #2523**_
Extend `Pinescript` with another language id as stated on the linked issue.
=> Enhance pinescript with extra id

src/iconsManifest/supportedExtensions.ts
> Starting with 1.0.0, husky can be configured using `.huskyrc`, `.huskyrc.json`, `.huskyrc.yaml`, `huskyrc.yml`, `.huskyrc.js` or `husky.config.js` file.
_Ref: https://github.com/typicode/husky#upgrading-from-014_
=> Extend husky icon to support husky.config.js

src/iconsManifest/supportedFolders.ts
For Java/Scala Play framework projects they have a conf folder. Ideally, this would show the same icon as the config folder currently it just shows the default icon.
=> Add conf to options for Config folder

src/iconsManifest/supportedFolders.ts
_**Fixes #2583**_
In Dart, it is a convention to use a `tool` folder: https://dart.dev/tools/pub/package-layout#internal-tools-and-scripts
This PR adds support for it within the same `tools` category.
=> feat: support tool folder within the tools category

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
e.g. [googletest](https://github.com/google/googletest/blob/master/BUILD.bazel) uses the .bazel extension and [many other projects](https://github.com/search?l=&q=extension%3Abazel+load&type=Code) seem to do so as well.
**TODO:**
=> add .bazel extension support for Bazel

src/iconsManifest/supportedExtensions.ts
Thought it'd be nice to add `COPYING`, `COPYING.md`, and `COPYING.txt` filename associations to the [license](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles/3fef37e26bb944b5303c1dbc813859f48c31e416#license) icon [for the GNU crowd](https://www.gnu.org/licenses/gpl-howto.html). And `COPYING.LESSER`, which I've just learned is the filename they recommend for the LGPL.
=> Add COPYING filename associations to license icon

src/iconsManifest/supportedExtensions.ts
_**References #2644, #2651**_
Just a quick follow-up to #2651—pretty sure the intent was to write `"unlicense", "unlicence"`, not `"unlicense"` twice. 👍🏼
```diff
{
icon: 'unlicense',
-  extensions: ['unlicense', 'unlicense'],
+  extensions: ['unlicense', 'unlicence'],
-  filenamesGlob: ['unlicense', 'unlicense'],
+  filenamesGlob: ['unlicense', 'unlicence'],
extensionsGlob: ['md', 'txt'],
filename: true,
format: FileFormat.svg,
},
```
=> Differentiate "unlicence" spelling variant

src/iconsManifest/supportedExtensions.ts
_**Fixes**_ N/A (search terms: [`gulpfile.mjs`](https://github.com/vscode-icons/vscode-icons/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+gulpfile.mjs))
---
Gulp supports the `.mjs` file extension for config files (tracked at https://github.com/gulpjs/interpret/issues/65).
It looks like `.cjs` is not supported yet (https://github.com/gulpjs/interpret/issues/68).
=> Add icon for Gulpfile.mjs

src/iconsManifest/languages.ts
It seems CFM extensions are using a new language id. I've kept the old one in case some extension is
still using it although I have reviewed all the cfm extensions and they don't seem to be supporting
anymore.
fixes #2673
=> fix(cfm): add more language ids

README.md
Link is currently broken because the casing doesn't match the filename.
=> Fix license link in readme

src/iconsManifest/supportedFolders.ts
This PR adds 'interface' as an alias for the 'interfaces' folder icon
=> Add alias for interfaces folder

src/iconsManifest/supportedExtensions.ts
Jest common/shared configuration file.
*.base.* and *.common.* pattern.
See https://github.com/facebook/jest/issues/3112 for an example.
=> Jest common/shared configuration file.

CHANGELOG.md
Just an incorrect URL I noticed while checking out the latest changes
=> Fix URL typo in changelog entry

.vscodeignore, CHANGELOG.md, package-lock.json, package.json
This version will be manually released by using docker instead of directly from @robertohuertasm mac machine. We suspect that this was causing #2165 again due to `.DS_Store` files being present. Hopefully, all this will get back to normal once we have travis again. On April 22 we will receive our first sponsorship which will allow us to pay for our release pipelines.
=> chore(v11.4.0): prepare new version

src/iconsManifest/supportedExtensions.ts
In my previous PR I accidentally included `filename: true`, but this icon should be for applied to any file with a `.pipeline` extension. For example: `example.pipeline`
=> Fix manifest entry for "pipeline"

.travis.yml, CHANGELOG.md
New 1.93.0 version makes the publication fail with an error saying that the The specified icon 'extension/images/logo.png' wasn't found in the extension.
I looked into vsce issues and there was one related which was closed without any answer in 2018. I'll get back to it at some point, but for the moment I will merge this to unblock our release.
=> fix(vsce): fix the vsce version

src/iconsManifest/supportedExtensions.ts
The list of supported filenames can be found on
https://github.com/postcss/postcss-load-config/blob/d1478640e823b5432b7dc43a0ba6e23c58b7b981/src/index.js#L77-L86
=> Add missing postcss config extensions

src/iconsManifest/supportedExtensions.ts
Currently `Chart.yaml` incorrectly has a Helm template language mode. However, it’s a regular YAML file. This has been corrected in https://github.com/Azure/vscode-kubernetes-tools/pull/948.
Both `Chart.lock` and `Chart.yaml` are related to Helm charts though. It makes sense to use the Helm icon.
The same could be said about `values.yaml` and `values.schema.json`, but personally I believe those names are too generic to assign a special icon to them.
=> feat(helm): Use Helm icon for Chart.lock and Chart.yaml

src/iconsManifest/supportedExtensions.ts
Apparently VS Code supports both [`devcontainer/devcontainer.json` and `.devcontainer.json` in the root of the project](https://code.visualstudio.com/docs/remote/create-dev-container#_create-a-devcontainerjson-file), so I added `.devcontainer.json` to the `extensions` field for the `devcontainer` icon.
Assuming that this change is okay, I'm unsure if I should update the Wiki or if that's something you do (or if it's automated). Just let me know!
=> Add .devcontainer.json to devcontainer file extensions

src/iconsManifest/languages.ts
`fortran_fixed-form` is being deprecated but it has been left in
for backwards compatibility
_**Fixes #2839**_
Not sure how you edit your CHANGELOG, but if you need me to update it let me know.
=> Adds support for `FortranFixedForm`

src/iconsManifest/supportedExtensions.ts
Use the prettier icon for `.prettierrc.toml`.
According to the [prettier config docs](https://prettier.io/docs/en/configuration.html), this is supported.
=> feat(prettier): support toml extension

README.md
Only these providers are supported: https://code.visualstudio.com/api/references/extension-manifest#approved-badges
=> fix(readme): use proper travis url for readme badges

src/iconsManifest/languages.ts
For those who don't use [`vscode-cudacpp`](https://marketplace.visualstudio.com/items?itemName=kriegalex.vscode-cudacpp) extension like me, `vscode-icons` will not change `*.cu` and `*.cuh` files' icon. The icon for "CUDA C++" item in `Select Language Mode` dialog box is also blank.
But there exsists a default language mode for CUDA called `cuda-cpp`, adding this to `ids` for `cuda` helps a lot.
=> Add `cuda-cpp` to `ids` item for cuda language.

src/iconsManifest/supportedExtensions.ts
Show icon for `gatsby-browser.tsx` and `gatsby-ssr.tsx` as Gatsby is working on supporting TS out of the box. 
=> feat(icon): add new extensionGlob for Gatsby

src/constants/index.ts
Changed the link in `constants` so that users can go directly to the [Releases](https://github.com/vscode-icons/vscode-icons/releases) page with the current release notes since the use of the previous one was stopped in December 2021.
=> fix(constants): make link in notification point to current release notes

src/iconsManifest/supportedExtensions.ts
_**Fixes #2947**_
.drawio extensionsGlob should be empty!
=> fix(drawio): extensionsGlob should be empty

src/iconsManifest/supportedExtensions.ts
From [commitlint docs](https://github.com/conventional-changelog/commitlint#shared-configuration): `.commitlintrc` configuration file is also supported.
=> Support .commitlintrc configuration file

src/iconsManifest/supportedExtensions.ts
tsconfig.eslint.json is commonly used in TypeScript eslint. 
It is also mentioned [in the docs](https://typescript-eslint.io/docs/linting/type-linting#i-get-errors-telling-me-the-file-must-be-included-in-at-least-one-of-the-projects-provided)!
=> refactor(eslint): add tsconfig.eslint.json

src/iconsManifest/manifestBuilder.ts, src/models/extensions/defaultExtension.ts, test/iconsManifest/manifestBuilder/files.test.ts, test/iconsManifest/manifestBuilder/folders.test.ts
Adds a new property to the `IDefaultExtension` interface to allow the usage of bundled icons.
This basically allows anyone to use not only custom icons but use the bundled icons as default folders and files. Note that only folder icons can be assigned to default folder and root_folder.
fix #3103
=> fix(defaults): allow to use bundled icons for default files/folders

package.json
The sponsor link is rendered in the header of the extension page in VSCode. For example:
=> chore(sponsor): add extension sponsor url

src/iconsManifest/supportedExtensions.ts
The new flat ESLint config system will only support `eslint.config.js`: https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new#configuration-file
N/A
=> feat(icon): support new eslint config system

package.json
Now we own the vscodeicons.team domain.
=> chore(domain): update vscode icons domain

src/iconsManifest/supportedExtensions.ts
Fixes [Icon Request]: deno.lock #3181
=> feat(deno): support for deno.lock

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the browserslist language registered by https://marketplace.visualstudio.com/items?itemName=webben.browserslist
=> feat(icon): support the browserslist language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the dockercompose language registered by https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker
_Fixes #3124_
=> feat(icon): support the dockercompose language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the drawio language registered by https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio
=> feat(icon): support the drawio language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the editorconfig language registered by https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
=> feat(icon): support the editorconfig language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the sass and sass.hover languages registered by https://marketplace.visualstudio.com/items?itemName=Syler.sass-indented
=> feat(icon): support the sass language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the browserslist language registered by https://marketplace.visualstudio.com/items?itemName=mrorz.language-gettext
=> feat(icon): support the po language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/nativeLanguageCollection.ts
This adds support for the csv language registered by https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv
=> feat(icon): support the csv language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the svg language registered by https://marketplace.visualstudio.com/items?itemName=jock.svg
=> feat(icon): support the svg language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the org language registered by https://marketplace.visualstudio.com/items?itemName=tootone.org-mode
=> feat(icon): support the org language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/nativeLanguageCollection.ts
This adds support for the yarnlock language registered by https://marketplace.visualstudio.com/items?itemName=mariusschulz.yarn-lock-syntax
=> feat(icon): support the yarnlock language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the sln language registered by https://marketplace.visualstudio.com/items?itemName=logerfo.sln-support
=> feat(icon): support the sln language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the excel language registered by https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer
=> feat(icon): support the excel language

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the go.mod and go.work languages registered by https://marketplace.visualstudio.com/items?itemName=golang.Go
There is also the related go.sum language, but the matching filename is sometimes associated with the go.mod icon, and sometimes with the go.work icon.
=> feat(icon): support the go.mod and go.work languages

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This adds support for the builtin `code-text-binary` language, which is used to represent binary files in VS Code.
=> feat(icon): support the code-text-binary language

src/iconsManifest/languages.ts
Both the `vim-help` and the `vim-snippet` languages are registered by https://marketplace.visualstudio.com/items?itemName=XadillaX.viml.
Because `vim-help` applies to `.txt` files matching a pattern, I thought it makes sense to treat them the same as `plaintext`. `vim-snippet` files uses extensions that may conflict with others, so I just added the language ID to the `viml` language.
This extension also registers the `vim-markdown` extension, which it shouldn’t (https://github.com/XadillaX/vscode-language-viml/pull/67).
This extension also registers the [`vroom`](https://github.com/google/vroom) language. I could only find a PNG icon for this. It’s just text with some colors, but I don’t know the font.
=> feat(icon): register the vim-help and vim-snippet languages

src/iconsManifest/supportedFolders.ts
This PR adds `__shared__` and `__share__` as aliases for the `shared` folder icon, similar to how the `tests` folder icon has the same support.
=> Add shared extensions

README.md
_**Fixes #3469**_
Change the link reference pointer in the [Bring your own icons](https://github.com/vscode-icons/vscode-icons?tab=readme-ov-file#bring-your-own-icons) section of the[ README](https://github.com/vscode-icons/vscode-icons/blob/master/README.md) to the [correct document](https://github.com/vscode-icons/vscode-icons/wiki/custom)
=> Fix wrong reference pointer in README.md

src/iconsManifest/supportedExtensions.ts
The `.package-lock.json` file is a version 3 lockfile that npm writes to the `node_modules` directory.
=> feat(icon): use npm icon for .package-lock.json

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts, src/models/language/languageCollection.ts
This registers the autoconf `m4`, `automake`, and `makefile2` languages. These are all defined by
https://marketplace.visualstudio.com/items?itemName=maelvalais.autoconf.
Since these are all GNU tools, the `gnu` icon was used for all of them.
=> feat(icon): use the gnu icon for autoconf files

src/iconsManifest/supportedExtensions.ts
Adding `.mjs` extension for tailwind config file icon
https://tailwindcss.com/blog/tailwindcss-v3-3#esm-and-type-script-support
=> add .mjs to tailwind config file

src/iconsManifest/supportedExtensions.ts
Microsoft began experimenting with the publishing of an XML-based solution format, and it has the extension `.slnx`.
reference: https://schwabencode.com/blog/2024/04/10/welcome-new-visual-studio-slnx-solution-file
=> feat(icon): supported `.slnx` file

.github/workflows/wpil.yml
Fixes `wpil` workflow.
I have replaced `nodegit` with `simple-git` in `vscode-icons/wpilgenerator`, which relies on the `git` binaries installed in the machine.
The workflow has been simplified as it doesn't need to checkout any repo for the `wpilgenerator` tool to work.
#3432 can be closed once this get merged.
=> Update wpil workflow

src/iconsManifest/supportedExtensions.ts
Stylelint has supported `.mjs` config file. This PR updates stylelint extensions by adding `.mjs`.
[stylelint.io/user-guide/configure](https://stylelint.io/user-guide/configure/)
=> feat: update stylelint extensions, add .mjs

src/iconsManifest/supportedExtensions.ts
Both `budget.json` and `budgets.json` are used by Lighthouse CI. Although there’s no default value, it’s a common convention to use one of these file names. See
https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md
=> feat(icon): use lighthouse icon for budget(s).json

src/iconsManifest/languages.ts
The `prototext` language ID is now treated the same as `proto` and `proto3`. It’s registered by
https://marketplace.visualstudio.com/items?itemName=pbkit.vscode-pbkit as well as
https://marketplace.visualstudio.com/items?itemName=dmitry-korobchenko.prototxt
=> feat(icon): support the prototext language

src/iconsManifest/supportedExtensions.ts
Since Nuxt v3.10.1, a `.config` folder can be used to place its config file. This PR makes sure to watch that folder too.
- https://github.com/nuxt/cli/pull/341
- https://github.com/nuxt/cli/releases/tag/v3.10.1
=> chore: support `nuxt` file

src/iconsManifest/supportedExtensions.ts
[According to the Next.js developers](https://github.com/vercel/next.js/discussions/35969#discussioncomment-10005034), support for the `next.config.ts` configuration file has been added, so I added support for this filename.
=> feat(icon): support `next.config.ts`

src/iconsManifest/supportedExtensions.ts
Yarn 4 writes this file into node_modules.
=> feat(icon): use yarn icon for .yarn-state.yml

src/iconsManifest/supportedExtensions.ts
- Add
Quasar Framework now supports `quasar.config.(js|mjs|cjs|ts)`:
- [`@quasar/app-vite v2` (release)](https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fapp-vite-v2.0.0-beta.1)
- [`@quasar/app-webpack v4` (release)](https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fapp-webpack-v4.0.0-beta.1)
=> feat: add Quasar's new config extensions

icons/file_type_language_configuration.svg, src/iconsManifest/supportedExtensions.ts
Language configuration files allow VSCode extensions to configure languages. See https://code.visualstudio.com/api/language-extensions/language-configuration-guide
These file names may prefix `language-configuration.json` with anything, but vscode-icons doesn’t support globs. Official extensions that come with VSCode use `.` as a separator, so I think it’s good to support that convention for the icon as well.
The language configuration format is part of Monaco editor, which is an integral part of VSCode. The icon was taken from the toolbar on https://microsoft.github.io/monaco-editor/.
=> feat(icon): add language-configuration icon

src/iconsManifest/supportedExtensions.ts
Adds support for all typedoc config file names: https://typedoc.org/options/configuration/#options
=> fix(typedoc): support additional config file names

src/iconsManifest/supportedExtensions.ts
See https://pnpm.io/pnpmfile.
The issue also mentions `global_pnpmfile.cjs`. I decided to not include that, as it’s non-standard.
_**Fixes #3256**_
=> feat(icon): support .pnpmfile.cjs

src/iconsManifest/supportedExtensions.ts
This PR adds a capture for `bun.lock`, the upcoming default lock file format for Bun (available in canary today). See https://x.com/bunjavascript/status/1866879040424120625
=> feat: add bun.lock to bun file types

src/iconsManifest/supportedExtensions.ts
Use the debian icon for aptfile.
_**Fixes #3119**_
=> feat(icon): support aptfile

src/iconsManifest/supportedFolders.ts
This uses the `app` folder icon for the `application` and `applications` folder. `app` is an abbreviation for `application`.
_**Fixes #3632**_
=> feat(icon): use app icon for application(s) folder

src/iconsManifest/languages.ts
Previously the `feature` language ID was used for cucumber files. Now the official extension uses the `cucumber` language ID.
_**Fixes #3248**_
=> feat(icon): add cucumber language ID

icons/file_type_cursorrules.svg, src/iconsManifest/supportedExtensions.ts
The `.cursorrules` file is used by Cursor editor. See https://docs.cursor.com/context/rules-for-ai.
The icon is based on their favicon.
The icon is not available as SVG, so I recreated it manually.
=> feat(icon): add icon for .cursorrules

icons/file_type_just.svg, src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts
The `just` language ID is registered by
https://marketplace.visualstudio.com/items?itemName=skellock.just and https://marketplace.visualstudio.com/items?itemName=kokakiwi.vscode-just.
I manually recreated the icon to match the favicon of https://just.systems by overlaying it.
https://plugins.jetbrains.com/plugin/18658-just provides a verion of the icon where the holes are transparent. To me the white dots on a black circle look seem pretty iconic.
It also looks pretty good in dark mode in my opinion, despite the outer circle being black.
_**Fixes #2679**_
=> feat(icon): add just icon

src/iconsManifest/supportedExtensions.ts
Support for `eleventy.config.mjs` was added in Eleventy 3.0.0.
See https://www.11ty.dev/docs/config/#default-filenames
=> feat(icon): support eleventy.config.mjs

src/iconsManifest/supportedExtensions.ts
with the prefix dot included, `vsicons-icon-theme.json` has `docusaurus.config..ts` as a generated value.
=> fix(docusaurus): correct extensionsGlob to not include prefix dot

src/iconsManifest/supportedExtensions.ts
The [Storybook Svelte CSF addon](https://github.com/storybookjs/addon-svelte-csf) allows us to write stories using `.stories.svelte` files.
This PR aims to display the Storybook icon for files with such extensions.
| Before | After |
|--------|--------|
| <img width="195" alt="Screenshot 2025-02-08 at 10 50 37" src="https://github.com/user-attachments/assets/7578abd8-a6a9-4507-90bd-9e5be3e43f62" /> | <img width="191" alt="Screenshot 2025-02-08 at 10 50 46" src="https://github.com/user-attachments/assets/2227f067-234d-48fd-831f-947d2016b2e4" /> | 
=> Add support for `svelte` extensions with Storybook

src/iconsManifest/supportedExtensions.ts, test/fixtures/supportedExtensions.ts
The icon was added in #3244, but the metadata was added in a test fixture instead of the builtin extensions file. This moves it into the proper file.
_**Fixes #3289**_
=> feat(icon): support the taskfile icon

.vscode/settings.json
Configure VSCode to trim final newlines from SVG files.
Personally I would prefer to always add a trailing newline, but this setting matches the current status quo.
=> chore(vscode): trim svg newlines

src/iconsManifest/supportedExtensions.ts
Maps sln to slnf as an additional extension
_**Fixes #3731 **_
=> Update to include slnf

src/iconsManifest/supportedExtensions.ts
_**Fixes #3733**_
Add `.git` file extension to the list which should use the git icon as file icon.
=> feat(icon): support for .git files inside git submodules

src/iconsManifest/supportedExtensions.ts
Add all supported extensions for *xo.config* files. See [v0.61.0-0 release notes](https://github.com/xojs/xo/releases/tag/v0.61.0-0):
> - Configuration now only through `package.json` and `xo.config.{js,cjs,mjs,ts,cts,mts}` files
=> Add more extensions for `xo.config` file

src/iconsManifest/languages.ts, src/iconsManifest/supportedExtensions.ts
VSCode 1.100 added support for the new `instructions` and `prompt` languages. THese are used for Copilot integration.
=> feat(icon): support instructions and prompt languages

src/iconsManifest/supportedExtensions.ts
SvelteKit now supports `svelte.config.ts` as a valid configuration file alongside `svelte.config.js`.
This PR updates the icon mapping to recognize and apply the existing `svelteconfig` icon for the `.ts` variant.
=> feat(svelte): add svelte.config.ts as svelteconfig extension

icons/file_type_light_shadcn.svg, icons/file_type_shadcn.svg, src/iconsManifest/supportedExtensions.ts
Both the icon and filename are based on https://ui.shadcn.com/docs/components-json.
_**Fixes #3664**_
=> feat(icon): add shadcn icon
