vscode-icons/vscode-icons

src/dev/extension.js

Now that updates coming from insider build daily, that's probably a good idea.

Implemented auto-reload vscode

---

README.md

We should add the code, otherwise any (non npm-User) will be confused, why are there so many errors while building.

Adding npm install

---

README.md

Add Custom Icon Packages to Readme

---

.github/CONTRIBUTING.md

######Fixes #134 Bug
####Changes proposed:
###Things I've done:
fixes numbering in guidelines.
Edit: Looks like headlines are not supported in Pull Requests.

fix numbering

---

.github/CONTRIBUTING.md

***Fixes #134***
inline code was wrong... Hope last fix referncing #134

fix inline code...again

---

README.md

add extension link

---

src/build/supportedExtensions.js

* `.pyd` - Python DLL
* `.pyo` - Python bytecode (optimized)
* `.pyw` - Python script for Windows

Add support for various Python filetypes

---

src/build/supportedFolders.js

This is the convention for HaxeFlixel projects (https://github.com/HaxeFlixel/flixel).

Use the dist folder icon for "export"

---

src/build/supportedExtensions.js

.pex is an XML format produced by this particle effect editor: http://onebyonedesign.com/flash/particleeditor/

Add .pex as an xml extension

---

src/build/supportedFolders.js

***Fixes #[ISSUE]***
Support 'sources' in plural as 'src' folder

Support 'sources' in plural as 'src' folder

---

src/build/supportedExtensions.js

Support license files with an .md extension

---

CHANGELOG.md
icons.json
src/build/supportedFolders.js

spec folder support

---

CHANGELOG.md
README.md
package.json
src/dev/extension.js
src/dev/messages.js
src/dev/messages_de.js
src/dev/settings.js

Feature drop160

---

src/build/supportedExtensions.js

.tmx files are created with the Tiled edtior (http://www.mapeditor.org/).

Add .tmx as an xml extension

---

icons.json
src/build/supportedExtensions.js

This PR assigns the angular icon for `angular-cli.json` file.

Assign Angular icon to angular-cli.json file.

---

.vscodeignore

***References #448***
[see this comment](https://github.com/robertohuertasm/vscode-icons/pull/448#issuecomment-261804358)

.ai and dockerfile removed from final package

---

package.json
typings/node.d.ts
typings/vscode-typings.d.ts

Remove redundant `typings` folder.

---

.gitignore
.vscodeignore
README.md
package.json
src/build/example.js
src/build/exampleGenerator.js
src/build/supportedFolders.js

I created this tool to help me preview how the new SVG icons will look in the editor and thought of sharing it with the rest.
**How it works:**
Read all about it in `README`.

Add ability to generate examples from icons.

---

icons.json
src/build/supportedExtensions.js

Adds the npm icon for [.npmrc files](https://docs.npmjs.com/files/npmrc).

Add .npmrc support

---

icons.json
src/build/supportedExtensions.js

Add 'conf' as config extension.

---

src/dev/extension.js

removed wrong line

---

icons.json
src/build/supportedExtensions.js

Add support for .gitconfig

---

README.md

I just went through and made sure that the grammar was OK. Your message was kept intact. By the way, thank you for this extension!!!!

Just making sure that the grammar is right.

---

jest.config.json
package.json
src/build/defaultSchema.js
src/build/iconGenerator.js
tests/iconGenerator.test.js

This PR introduces a first batch of tests to the project, using [Jest](https://facebook.github.io/jest/) testing.

Add tests to the project.

---

.eslintrc.json
CHANGELOG.md
package.json
src/build/defaultSchema.js
src/build/iconGenerator.js
src/dev/extVersion.js
tests/iconGenerator.test.js

changelog update.
prebuild step added to npm scripts.

eslint applied to the latest changes.

---

src/build/supportedExtensions.js

How did that `dot` got there? Must had a bad weekend...

Fix jest related extension.

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

@robertohuertasm This PR is subjected to your discretion. Reject it if you feel so.

Update the github templates, removing the 'lint' & 'build' suggestions.

---

src/build/defaultSchema.js
src/build/iconGenerator.js
tests/iconGenerator.test.js

Add support for light icon version.

---

README.md

Fix ratings badge link to point to marketplace.

---

.gitattributes

Simplify the declarations.

---

src/build/iconGenerator.js
tests/iconGenerator.test.js

This PR was originally created by @JimiC but it was closed by mistake.
Related to #535

Jimi c light support improved

---

test/iconGenerator.test.js

Getting back tests

---

CHANGELOG.md
icons/file_type_vscode@2x.svg
src/build/supportedExtensions.js

vscode icon transformed to svg

---

README.md

fix small error in readme

---

icons/file_type_polymer@2x.svg
src/build/languages.js
src/build/supportedExtensions.js

This adds a [Polymer](https://www.polymer-project.org/1.0) icon and sets to the language ID from [`language-polymer`](https://github.com/JonathanWolfe/language-polymer).

Add Polymer icon

---

src/build/languages.js
src/build/supportedExtensions.js

Add support for reStructuredText syntax.

---

src/build/languages.js
src/build/supportedExtensions.js

Add support for properties language id.

---

src/build/supportedExtensions.js

Add support for Swift "Package.pins".

---

icons/file_type_crystal@2x.svg
src/build/languages.js
src/build/supportedExtensions.js

***Fixes #[ISSUE]***
[short comment]
add Crystal-lang icon

Add Crystal icon

---

package.json

test added to tslint

---

package.json

Improve npm test script in package.json to always compile before testing

---

.vscode/launch.json

Remove redundant 'outFiles' declaration for test debugging.

---

test/iconGenerator.test.ts

Enable disabled test case.

---

.vscode/launch.json

Reverts robertohuertasm/vscode-icons#592

Revert "Remove redundant 'outFiles' declaration for test debugging."

---

src/icon-manifest/supportedExtensions.ts

test ts back

---

CHANGELOG.md
README.md
package.json
src/index.ts

Lodash added to dependencies

---

README.md

Update badges links in README.

---

.vscode/extensions.json

Add recommended extensions.

---

src/icon-manifest/iconGenerator.ts
test/iconGenerator.test.ts

***Fixes #631***
Test have also been added.

Add support for light theme language ids.

---

src/commands/index.ts
src/icon-manifest/build.ts
src/icon-manifest/iconGenerator.ts

***Fixes #635, fixes #636  ***

Restore Command and Build process are reliable again

---

package.json
yarn.lock

I grew tired of having to clean the `out` folder manually every time I had to compile the project.

Clean 'out' folder before compilation.

---

README.md

Add dependencies status badges.

---

README.md

Trivial improvement to have similar topics closer together.

Move 'configuration' section closer to 'customizing' section.

---

src/index.ts
src/init/autoDetectProject.ts
src/models/vscode/index.ts
src/models/vscode/vscode.ts
src/models/vscode/vscodeUri.ts
src/utils/index.ts
src/utils/vscode-extensions.ts
test/autoDetectProject.test.ts

Auto detection now searches in subfolders too to determine if the opened project should show specific icons.

Improve the auto detection feature.

---

src/icon-manifest/iconGenerator.ts
test/iconGenerator.test.ts

Fix issue with light version icons overriding associated icons.

---

CHANGELOG.md
README.md
package.json
src/settings/extensionSettings.ts
tsconfig.json

7.1.0 release

---

README.md

I'm using [Grammarly](https://www.grammarly.com/).

Fixes several spelling and grammar issues.

---

src/icon-manifest/manifestMerger.ts

Fix build process to use enabled ng icons.

---

README.md

Fix grammar error.

---

src/commands/index.ts
src/index.ts
src/init/autoDetectProject.ts
src/messages/index.ts
test/autoDetectProject.test.ts

Improve the canceling behavior of auto project detection.

---

.vscodeignore

Exclude .editorconfig file from the distribution.

---

src/icon-manifest/supportedExtensions.ts

See:
- http://hashlink.haxe.org/
- https://github.com/HaxeFoundation/hashlink

Add hl (HashLink) to binary extensions

---

src/icon-manifest/supportedExtensions.ts

(ilk files are created by the linker, see https://msdn.microsoft.com/en-us/library/1716cz97.aspx)

Add ilk to binary extensions

---

src/icon-manifest/supportedExtensions.ts

Just added a few more terraform extensions

Added tfvars, tfstate and tfstate.backup to terraform extensions

---

.bithoundrc
README.md
package.json
yarn.lock

I strongly recommend adding [bithound](https://www.bithound.io)'s dependencies and code analysis support to the project. It's really valuable.
https://www.bithound.io/popular

Add support for bithound analysis.

---

package.json
src/i18n/langResources/lang.de.ts

Reminder to myself: Never assume that when it works on `Windows` it works on `Linux` too.

Fix linting on Linux.

---

.bithoundrc
src/i18n/langResources/lang.de.ts
src/i18n/langResources/lang.en.ts
src/i18n/langResources/lang.es.ts

Consistency fix

---

test/manifestMerger/defaultExensions.test.ts

Fix thread raising issue when deleting files.

---

README.md
src/i18n/langResourceCollection.ts
src/i18n/langResources/index.ts
src/i18n/langResources/lang.es.ts
src/i18n/langResources/lang.fr.ts

Translation is a courtesy of my sister Eve.

Add French translation.

---

test/manifestMerger/defaultExensions.test.ts
test/manifestMerger/fileExtensions.test.ts
test/manifestMerger/folderExtensions.test.ts

Fix the failed file delete issue with default extensions tests.

---

src/icon-manifest/supportedExtensions.ts

Added tsx specs and tests

---

src/icon-manifest/supportedExtensions.ts

Associate 'postcss.config.js' with postcss icon.

---

src/icon-manifest/supportedExtensions.ts

Add support for the ignore file.

Update supportedExtensions.ts for stylelint

---

src/icon-manifest/supportedExtensions.ts

Assign '.drone.yml.sig' filename to drone icon.

---

src/icon-manifest/supportedExtensions.ts

***Fixes #828***
Add an alias extension ".jestrc" for Jest config files

Add .jestrc extension for Jest

---

src/icon-manifest/supportedExtensions.ts

Support for scssm

---

.vscodeignore

Once again forgot to do this. 😞

Exclude AppVeyor config file from distribution.

---

src/commands/index.ts
src/icon-manifest/manifestMerger.ts
test/manifestMerger/presets.test.ts

Fix default folder not showing in light theme after apply customization.

---

src/icon-manifest/supportedFolders.ts

Associate 'submodules' with 'git' folder icon.

---

src/commands/index.ts

***Fixes #923***
@robertohuertasm Consider a patch release.

Fix null reference of PAD result object.

---

src/index.ts
src/init/welcome.ts

Fix new version check flow.

---

src/icon-manifest/supportedFolders.ts

Add support for html folder.

---

CHANGELOG.md
package.json
src/settings/extensionSettings.ts

preparing 7.8.0 version

---

CHANGELOG.md
package.json
src/settings/extensionSettings.ts

Preparing 7.8.1

---

src/init/autoApplyCustomizations.ts

Fix condition check for user configuration settings.

---

package.json
src/models/vscode/vscodeCancellationToken.ts
yarn.lock

Update dependencies and fix liniting issues.

---

package-lock.json

Add support for npm 5.

---

CHANGELOG.md
package.json
src/settings/extensionSettings.ts

preparing 7.9.0

---

src/icon-manifest/manifestMerger.ts

Fix lodash remove predicate parameter.

---

README.md

a few more examples with icons customizations

---

.vscodeignore

YAFE = (Yet another forgotten exclusion)

Exclude package-lock.json from distro.

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/init/applyCustomizationsManager.ts
src/settings/extensionSettings.ts

Fixes #1042 
This is a fix but still we don't know why the first detection is triggered. I didn't have much time so I'll publish the fix and leave the investigation for another time.

getting ready for 7.10.1

---

src/init/welcome.ts

Just caught it unintentionally when I updated this extension.

Remove redundant point

---

.vscode/launch.json
.vscode/tasks.json

Switching to tasks v2.0.0 and launch v0.2.0

---

package-lock.json
package.json
src/models/settings/settings.ts
src/settings/settingsManager.ts
yarn.lock

Add types for semver.

---

src/models/settings/settings.ts
src/settings/settingsManager.ts
test/settings/settings.test.ts

***Fixes #1101***
Also, adds support for `code-oss-dev`.

Add support for OSS version.

---

CHANGELOG.md
package-lock.json
package.json
src/settings/extensionSettings.ts

New release including the fix for the welcome message

---

src/init/welcome.ts

Not display welcome message when extension is already active.

---

src/icon-manifest/supportedFolders.ts

***Fixes #1120***
[short comment]

add doc folder support

---

README.md
yarn.lock

typo found

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Proposed changes to templating.

Improve templates.

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/settings/extensionSettings.ts

preparing 7.15.0

---

src/icon-manifest/supportedFolders.ts

Add extensions folders to plugin folder icon.

---

src/icon-manifest/languages.ts
src/icon-manifest/supportedExtensions.ts
src/models/language/languageCollection.ts

Cake is not a language id anymore

---

package.json

Get rid of `bithound`'s own security notice.

Remove bithound dependency and script.

---

package.json

As requested in https://github.com/vscode-icons/vscode-icons/issues/1236#issuecomment-340621654.

Add multi-root ready keyword in package.json.

---

src/icon-manifest/supportedExtensions.ts

Add `.prettierignore` to prettier icon

---

src/icon-manifest/supportedExtensions.ts

Extend Storybook supported extensions.

---

README.md

Update README.md: Docs

---

src/icon-manifest/supportedExtensions.ts

Add webpack.prod.conf.js support

---

src/icon-manifest/supportedFolders.ts

Map `screenshot(s)?` to `image` folder icon

---

README.md

It doesn't render in `vscode` marketplace.

Replace GitHub Emoji of right arrow.

---

.gitmodules
.travis.yml
package-lock.json
package.json
yarn.lock

This PR adds the ability to auto-detect when the list of files and folders has changed, generate the new list and deploy that list to the corresponding wiki page.
The tool has been added to a separate project @ https://github.com/vscode-icons/wpilgenerator and is used here as a submodule.

Add wiki page icons list generator as submodule.

---

src/icon-manifest/supportedExtensions.ts

Added .stylelintcache

---

package-lock.json
yarn.lock

Fix package managers lock files.

---

.travis.yml
docker/development/Dockerfile
docker/development/build.sh
docker/development/install.sh
docker/remote-builder/Dockerfile
docker/remote-builder/build.sh
docker/trigger-docker-vsi.sh

Change docker image build process.

---

src/icon-manifest/supportedExtensions.ts

Adds support for conanfile.py

---

src/icon-manifest/manifestReader.ts

At some point, I'd like to add some test cases for that.

Fix toggling of preset icons

---

test/init/projectAutoDetection.test.ts

Use sinon syntax sugar for promises.

---

README.md
test/iconGenerator/functionality.test.ts
wallaby.js

_**Resolves #1492**_
Wow. `Wallaby.js` is so much more than `Mocha` itself. Finally, the test runner I was looking for. This tool sheds light on every "dark" corner of your project. It shows you the **real** code coverage.

Add Wallaby integration

---

package.json

Fixes _**#1524**_
No more preview tag

no more preview tag

---

package.json

Reverts vscode-icons/vscode-icons#1525

Revert "no more preview tag"

---

CHANGELOG.md
package-lock.json
package.json
src/settings/extensionSettings.ts

preparing 7.22.0

---

package.json
src/cleanUp/index.ts
src/uninstall.ts
test/cleanUp/cleanUp.test.ts
test/utils/utils.test.ts

Add uninstall hook script (cleanUp)

---

.vscodeignore

Remove wallaby.js from distribution

---

README.md

fixed link in the readme

---

src/icon-manifest/supportedExtensions.ts

[List of a browserslist sources](https://github.com/browserslist/browserslist#queries)

[extensions] Update browserslist extensions

---

src/icon-manifest/languages.ts

Fixed as per [this comment](https://github.com/vscode-icons/vscode-icons/pull/1546#issuecomment-386278472)

fixed jsonc default extension

---

.appveyor.yml

Simplified how `AppVeyor` installs latest `Yarn` version.

Improve AppVeyor config

---

src/icon-manifest/languages.ts
src/icon-manifest/supportedExtensions.ts
src/models/language/languageCollection.ts

_**Fixes #1605**_
Adds `jenkinsfile` support via the languageId `jenkins`

Support Jenkins via language Id

---

src/icon-manifest/supportedExtensions.ts

Associate 'plist' with config icon

---

package.json
src/cleanUp/index.ts
src/constants/index.ts
src/icon-manifest/iconGenerator.ts
src/models/settings/settings.ts
src/settings/settingsManager.ts
src/utils/index.ts
test/cleanUp/cleanUp.test.ts
test/iconGenerator/functionality.test.ts
test/manifestMerger/defaultExtensions.test.ts
test/manifestMerger/fileExtensions.test.ts
test/manifestMerger/folderExtensions.test.ts
test/settings/settings.test.ts

_**Fixes #1649**_
Probably also suits #1572

Add support for portable mode

---

src/cleanUp/index.ts
src/errorHandler.ts
src/icon-manifest/iconGenerator.ts
src/settings/settingsManager.ts

Notation:
- Handled Error: Any error that we log and we are determining (handling) the flow.
- Unhandled Error: Any error that we log and we are not determining (handling) the flow or handling is not needed.
Using this error logger we can quickly determine if the error was registered by us or not, and what type it was.

Improve error handling

---

CHANGELOG.md

Fix the latest released changelog

---

src/icon-manifest/supportedFolders.ts

As per requested in #650 [comment](https://github.com/vscode-icons/vscode-icons/issues/650#issuecomment-409748956)

Add svg to the image folders

---

.prettierignore
.prettierrc
.vscode/launch.json
.vscode/tasks.json
src/commands/index.ts
src/icon-manifest/manifestMerger.ts
test/errorHandler.test.ts
test/iconGenerator/iconGeneration-files.test.ts
test/iconGenerator/iconGeneration-folders.test.ts
tsconfig.json
tslint.json

Apply prettier formatting for JSON.
Adjust line length.
Adjust arrow functions.
Fix grammar.

Refactor for Prettier

---

CHANGELOG.md

Spelling correction

---

src/icon-manifest/supportedExtensions.ts

This is basically an uncompressed version of .ods

Add .fods extension for "Flat XML ODF Spreadsheet"

---

src/icon-manifest/supportedExtensions.ts

Fixes missing extension entries.

Fix supported file entry

---

src/icon-manifest/supportedExtensions.ts

Icon support for .mailmap extension

---

CHANGELOG.md
package-lock.json
package.json

preparing 7.27.0

---

CHANGELOG.md

Update CHANGELOG.md fix typo in changelog

---

CHANGELOG.md
package-lock.json
package.json

I propose making this release prior to the v.8 release so we do 2 separated ones. This time maybe we have two releases not really that much separated in time as we are used to lately but that's ok. v8 deserves it's own release.

preparing 7.28.0

---

.travis.yml
package.json

- Fix publication stage
- Fix docker stages
- Fix wiki pages icons list generator stage

Fix CI issues

---

.appveyor.yml
.travis.yml

Adds node version to test against insiders version.

Add node version for vscode insiders

---

package.json

Make greenkeeper ignore `vscode` dependecy

---

src/iconsManifest/supportedExtensions.ts

added support for npm-shrinkwrap.json

---

.vscode/extensions.json

Removing deprecated extension and adding new recommended for `tslint`.

Update recommended extensions

---

CHANGELOG.md
package-lock.json
package.json

prepare next release

---

CHANGELOG.md
README.md
package-lock.json
package.json

_**Fixes #1908 **_
This PR just updates the publisher name.

updated publisher name

---

src/iconsManifest/supportedFolders.ts

_**related #650**_
Added more configuration folders.

support for more config folder extensions

---

src/iconsManifest/supportedFolders.ts

_**Related #650**_
Support for `library` folder

support for library folder

---

CHANGELOG.md
package-lock.json
package.json

Prepare next

---

src/iconsManifest/supportedExtensions.ts

feat(icons): add support for old vsts-ci extension

---

CHANGELOG.md
package-lock.json
package.json

If you are ok, we're releasing this today!

docs(changelog): prepare next release changelog

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare 8.7.0

---

icons/file_type_stencil.svg
src/iconsManifest/languages.ts
src/iconsManifest/supportedExtensions.ts
src/models/language/languageCollection.ts

Add support for Stencil

---

CHANGELOG.md
package-lock.json
package.json

@KingDarBoja, you should add your email or/and your website to the package.json! 
Welcome to the team! ❤️

chore(release): prepare 8.8.0

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare 9.0.0

---

CHANGELOG.md
package.json

fix(vscode): use same version of the vscode engine to make vsce happy

---

greenkeeper.json
package-lock.json
package.json

Correct `vscode` engine version

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare version 9.1.0

---

CHANGELOG.md

chore(release): fix version number

---

icons/file_type_vlang.svg
src/iconsManifest/languages.ts
src/iconsManifest/supportedExtensions.ts
src/models/language/languageCollection.ts

More info: https://vlang.io/
VSCode extension: [marketplace](https://marketplace.visualstudio.com/items?itemName=0x9ef.vscode-vlang&ssr=false)

Add support for V lang

---

src/iconsManifest/supportedFolders.ts

CHANGED
['dist', 'out', 'export', 'build', 'release', 'target']
TO
['dist', 'dists', 'out', 'outs', 'export', 'exports', 'build', 'builds', 'release', 'releases', 'target', 'targets']

Added extensions to icon dist

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare 9.4.0

---

icons/file_type_inc.svg

Add background to include icon

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare 9.5.0

---

src/iconsManifest/supportedExtensions.ts

nothing
Add `gridsome.client.js|ts`
ref: https://gridsome.org/docs/client-api/#usage-in-plugins

feat: Add support gridsome.client.js for Gridsome

---

src/iconsManifest/supportedExtensions.ts

related issue: https://github.com/rollup/rollup/pull/3204/files

support mjs config file extension for rollup

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare 9.6.0

---

package-lock.json
package.json

chore(release): update version

---

src/iconsManifest/supportedExtensions.ts

Add support for zipx extension

---

src/iconsManifest/supportedFolders.ts

_**References #650**_
https://github.com/vscode-icons/vscode-icons/issues/650#issuecomment-579586180

Extend folder icons with plural "libs"

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare next release

---

.travis.yml
.vscode/extensions.json
greenkeeper.json
package-lock.json
package.json

- Add peer dependency of `tslint` for `eslint-plugin-tslint`
- Switch recommended extension from `tslint` to `eslint`
- Add `tslint` to ignored dependencies of `greenkeeper`
Info on `tslint` peer dependency: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin-tslint/package.json#L39

fix(dependencies): fix several issues with project's dependencies

---

.appveyor.yml
.travis.yml

fix(ci): Fix ci configs

---

.lintstagedrc

As I learn more about our devops tools, I realize that some mistakes were made.

Correct eslint syntax

---

.travis.yml

Forgot a crucial part. Merging asap.

Allow Windows builds to fail on Travis CI

---

src/iconsManifest/supportedExtensions.ts

Correct `nsri` config file association

---

src/iconsManifest/supportedExtensions.ts

Extend zeit icon to vercel files

---

src/iconsManifest/supportedFolders.ts

Added `.storybook` file name to `story` extensions.

---

icons/file_type_spacengine.svg
src/iconsManifest/supportedExtensions.ts

Add support for Spacengine

---

src/iconsManifest/languages.ts

Update mlang ids based on new extension

---

src/iconsManifest/supportedExtensions.ts

Add support for .snupkg files

---

src/iconsManifest/supportedFolders.ts

_**References #650**_
Add clients extension
https://github.com/vscode-icons/vscode-icons/issues/650#issuecomment-715363548

Add clients extension

---

icons/file_type_typedoc.svg
src/iconsManifest/supportedExtensions.ts

Add support for TypeDoc

---

CHANGELOG.md
package-lock.json
package.json

Ready to do the first release of the year!

chore(11.1.0): prepare new release

---

src/iconsManifest/supportedExtensions.ts

https://stylelint.io/user-guide/configure

add more extension to stylelint

---

src/iconsManifest/supportedExtensions.ts

Add mdx storybook file support

---

src/iconsManifest/supportedExtensions.ts

Support for **all** *Serverless Framework* configuration **file extensions**.
For more information: <https://www.serverless.com/framework/docs/providers/aws/guide/intro/>

Support all Serverless Framework configuration file extensions

---

CHANGELOG.md
package-lock.json
package.json
src/iconsManifest/supportedExtensions.ts

Another manual release due to Travis not working nice with OSS...

chore(11.2.0): prepare new release

---

CHANGELOG.md
README.md
package-lock.json
package.json

Changelog changes and new gold sponsor for our project which will enable Travis! 🚀

chore(11.3.0): prepare new release

---

package.json

feat(vscode): untrusted workspaces support

---

src/iconsManifest/languages.ts
src/iconsManifest/supportedExtensions.ts
src/models/language/languageCollection.ts

feat(log): support for language id

---

package.json

feat(vscode): virtual workspace support

---

CHANGELOG.md
package-lock.json
package.json

chore(version): prepare release 11.5.0

---

src/iconsManifest/supportedExtensions.ts

feat(xlsb): support for binary format

---

src/iconsManifest/languages.ts

feat(rails): support for html.erb lang id

---

CHANGELOG.md
package-lock.json
package.json

chore(11.6.0): prepare next release

---

src/iconsManifest/supportedFolders.ts

Add the default cypress test folder

Add the default cypress test folder

---

src/iconsManifest/supportedExtensions.ts

Next.js 12 added support for configuring the framework via `next.config.mjs`, as seen in [their announcement blog post](https://nextjs.org/blog/next-12#other-improvements).

feat: mjs config support for Next.js

---

README.md

Also the dependency status badges are broken.

Update travis ci build badge

---

src/iconsManifest/supportedExtensions.ts

Add `.tool-versions` filetype support for [asdf](https://asdf-vm.com/) version manager 

feat(icon): support for .tool-versions

---

icons/file_type_k.svg
src/iconsManifest/languages.ts
src/iconsManifest/supportedExtensions.ts
src/models/language/languageCollection.ts

feat(icon): support for shakti

---

src/models/extensions/defaultExtension.ts
src/models/extensions/extension.ts
src/models/extensions/fileExtension.ts

style: change to jsdoc

---

src/iconsManifest/languages.ts

feat(lisp): autolisp support

---

src/iconsManifest/supportedExtensions.ts

feat(astro): support astro.config.ts

---

.github/workflows/test.yaml

Based on previous work made by @Snazzah

ci(coverage): add test coverage

---

src/iconsManifest/supportedExtensions.ts

feat(icon): add .lighthouserc cjs extension

---

icons/file_type_wgsl.svg
src/iconsManifest/languages.ts
src/iconsManifest/supportedExtensions.ts
src/models/language/languageCollection.ts

feat(icon): add WebGPU Shader Language (wgsl) icon

---

test/utils/utils.test.ts

fix: typo fix in utils.test.ts

---

package-lock.json
package.json

chore(version): bump to 11.20.0

---

.gitignore
package-lock.json
package.json
src/constants/index.ts
src/index.web.ts
webpack.config.ts

Support for icons in the web. This version just shows the icons but doesn't support commands.

feat(web): minimal web support

---

.vscode/launch.json

feat(web): allow to launch web version

---

package.json

fix(activationEvent): use onStartupFinished

---

package-lock.json
package.json

chore(version): bump to 12.1.0

---

README.md
package-lock.json
package.json

updates the version
_**Fixes #3217**_

fix(badges): update readme badges

---

src/iconsManifest/languages.ts
src/iconsManifest/supportedExtensions.ts

fix(assembly): added common files and new language ids

---

src/iconsManifest/languages.ts
src/iconsManifest/supportedExtensions.ts

feat(kotlin): support for new ids and extensions

---

test/iconsManifest/specsExtensions.test.ts

test(msg): better message for file tests

---

package-lock.json
package.json

chore(version): bump to 12.4.0

---

README.md

fix(readme): fix badges

---

src/iconsManifest/supportedFolders.ts

fix(docs): fixes error in prev PR

---

src/iconsManifest/supportedExtensions.ts

https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

feat(rust-toolchain): support for rust-toolchain.toml

---

src/iconsManifest/supportedExtensions.ts

feat(icon): add icon for `go.work.sum`

---

src/iconsManifest/supportedFolders.ts

feat(icon): Update python folder icon to include __pycache__

---

src/iconsManifest/supportedExtensions.ts

See https://docs.datadoghq.com/static_analysis/?tab=circleciorbs

feat(datadog): support for static analysis files

---

src/iconsManifest/supportedExtensions.ts

fix(datadog): add proper suffix

---

src/iconsManifest/supportedExtensions.ts
test/fixtures/supportedExtensions.ts

This adds support for the docker-compose.debug.yml file.

feat(icon): add support for docker-compose.debug

---

src/iconsManifest/supportedExtensions.ts

_**Fixes #3222**_
Update extensions list to [all default configuration filenames for Eleventy](https://www.11ty.dev/docs/config/#default-filenames).

Update extensions for Eleventy icon

---

src/iconsManifest/languages.ts

feat(icon): support the systemd-conf language

---

src/iconsManifest/supportedExtensions.ts

feat(icon): add cjs and mjs extensions for .mocharc

---

README.md

fix(readme): update extension path

---

src/iconsManifest/supportedExtensions.ts

feat(icon): associate .tiltignore with tilt

---

.github/CONTRIBUTING.md

None
**Context:**
I saw that many PRs were rejected because people were pushing to their `master` branch (I did it too); so I'm trying to save them (and yourself) some time by specifying not to in the contributing guide.

docs(contributing): specify creating a branch for PRs

---

package-lock.json
package.json
src/iconsManifest/supportedFolders.ts

chore(version): bump to 12.8.0

---

package-lock.json

chore(deps): run audit fix

---

src/iconsManifest/supportedExtensions.ts

Update commitlint extensions based on https://commitlint.js.org/reference/configuration.html.

feat: update commitlint extensions

---

src/iconsManifest/supportedExtensions.ts

This is an image format.
_**Fixes #3519**_

feat(icon): support the heic extension

---

src/iconsManifest/supportedExtensions.ts

These files are detected automatically by vitest for type tests.
https://vitest.dev/guide/testing-types#testing-types

feat(icon): sets 'testts' for 'test-d' files

---

src/iconsManifest/supportedExtensions.ts

feat(icon): support `playwright.config.mts`

---

icons/file_type_jsr.svg
src/iconsManifest/supportedExtensions.ts

feat(icon): add the jsr icon

---

src/iconsManifest/languages.ts

See https://github.com/DeltaXML/vscode-xslt-tokenizer/blob/20b6aa257da710a7c35b7e1e82358789caf4244b/package.json#L817-L825
_**Fixes #3252**_

feat(icon): consider xslt language an alias of xsl

---

src/iconsManifest/languages.ts

This language was introduced in
https://github.com/bazel-contrib/vscode-bazel/pull/379

feat(icon): support the bazelrc language

---

src/iconsManifest/languages.ts
src/iconsManifest/supportedExtensions.ts

🎉 We now have bun lock as text: https://bun.sh/blog/bun-lock-text-lockfile

feat(icon): add bun.lock for bun

---

src/iconsManifest/supportedFolders.ts

feat(icon): use the www icon for the .web folder

---

src/iconsManifest/supportedFolders.ts

feat(icon): use the fonts folder icon for webfonts

---

.github/workflows/svg-icon-check.yml

Adds a new workflow to check the contributed icons and verify how the look on different background colors.
Example of how this should look like (extracted from a test project):

ci(images): check icons in different backgrounds

---

icons/file_type_stackblitz.svg
src/iconsManifest/supportedExtensions.ts

The icon was taken from the user interface of a Stackblitz project.
The filename was taken from
https://developer.stackblitz.com/platform/webcontainers/project-config

feat(icon): add the stackblitz icon

---

src/iconsManifest/supportedExtensions.ts

This is an experimental configuration file for Node.js. See https://nodejs.org/docs/latest/api/cli.html#--experimental-default-config-file

feat(icon): support node.config.json

---

src/iconsManifest/supportedFolders.ts

feat(icon): add support for additional image file extensions

---

package-lock.json
package.json

chore(version): update version and audit fix

---

src/iconsManifest/supportedExtensions.ts

feat(icon): add cjs extension for hardhat.config.cjs

---

src/iconsManifest/supportedExtensions.ts

feat(icon): add support for .cursorignore

---

src/iconsManifest/languages.ts
src/iconsManifest/supportedExtensions.ts

This is a new language that’s registered by the Docker extension.

feat(icon): add support for dockerbake

---

src/iconsManifest/supportedExtensions.ts

_**Fixes #3762**_
I'm not entirely sure this is the best way to add it, any suggestions for improvements would be welcome.

feat(icon): support project-specific paket.template and paket.references

---

src/iconsManifest/supportedExtensions.ts

related https://github.com/streetsidesoftware/cspell/pull/7531

feat(icon): `cspell.config.mjs` is actually supported
